# Generated by Django 6.0.2 on 2026-03-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonagemHarryPotter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('casa', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('patrono', models.CharField(max_length=100)),
            ],
        ),
    ]
