# Generated by Django 6.0.2 on 2026-03-27 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('cor', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MaeDoPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=100)),
                ('pets', models.ManyToManyField(related_name='maes', to='belinhapets.pet')),
            ],
        ),
    ]
