# Generated by Django 6.0.2 on 2026-03-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dupla_um', models.CharField(max_length=120)),
                ('dupla_dois', models.CharField(max_length=120)),
                ('horario', models.DateTimeField()),
                ('local', models.CharField(max_length=150)),
                ('placar_dupla_um', models.PositiveIntegerField(blank=True, null=True)),
                ('placar_dupla_dois', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'ordering': ['horario'],
            },
        ),
    ]
